config/routes.rb
Rails.application.routes.draw do
  get 'ranking/index'
  get 'pages/home'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get '/users/auth/line', to: 'users/omniauth_callbacks#line'
  get '/users/auth/line/callback', to: 'users/omniauth_callbacks#line'

  root 'pages#home'
  resources :movies, only: [:index, :show, :destroy] do
    resources :reviews, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
    member do
      post 'vote', to: 'votes#vote'
    end
  end
  
  post 'movies/fetch_movies', to: 'movies#fetch_movies', as: 'fetch_movies'
  get 'admin', to: 'admin#index'  # 管理者用トップページ
  post 'admin/reset_vote_count', to: 'admin#reset_vote_count'  # 投票数リセット
  get 'ranking', to: 'ranking#index'
  
  post 'oauth/callback', to: 'google_oauths#callback', as: :oauth_callback_post
  get 'oauth/callback', to: 'google_oauths#callback', as: :oauth_callback_get
  get 'oauth/:provider', to: 'google_oauths#oauth', as: :auth_at_provider

  get '/reviews_ranking', to: 'ranking#reviews_ranking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :votes, dependent: :destroy 
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]
  has_many :reviews, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  has_many :likes, dependent: :destroy

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  # before_save :set_default_avatar, if: -> { avatar.blank? } 

  # private

  # def set_default_avatar
  #   default_avatar_path = Rails.root.join('public/images/fallback/sample.jpg')  # 正しいパスでデフォルトを参照
  #   self.avatar = File.open(default_avatar_path) if File.exist?(default_avatar_path)  # ファイルが存在する場合に設定
  # end
  def self.from_omniauth(auth)
    where(line_user_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.line_user_id = auth.uid  # LINEのユーザーID
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.order(:id)  # ユーザーをIDで昇順に並べる
  end

  def reset_vote_count
    user = User.find_by(id: params[:user_id])  # ユーザーIDで検索
    if user
      # ユーザーの投票を全て削除
      Vote.where(user_id: user.id).destroy_all
  
      # 投票数をリセット
      user.update(vote_count: 0)
  
      flash[:notice] = "ユーザー#{user.name}の投票数をリセットしました。"
    else
      flash[:alert] = "ユーザーが見つかりません。"
    end
  
    # 管理画面にリダイレクト
    redirect_to admin_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review

  def create
    @like = @review.likes.create(user: current_user)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to movie_path(@review.movie.id) }
    end
  end

  def destroy
    @like = @review.likes.find_by(user: current_user)
    @like&.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to movie_path(@review.movie.id) }
    end
  end

  private

  def set_review
    @review = Review.find(params[:review_id])
    @movie = @review.movie  
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @movies = Movie.order(release_date: :asc) 
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!  # ユーザー認証が必要な場合
  
  def vote
    # 映画をidで検索
    @movie = Movie.find_by(id: params[:id])
    
    if @movie.nil?
      flash[:alert] = t('movies.not_found')  # 映画が見つからない場合のメッセージ
      redirect_to movies_path
      return
    end
    
    # ユーザーの総投票数を確認
    user_total_votes = Vote.where(user_id: current_user.id).count
    
    # ユーザーが特定の映画に投票しているか確認
    user_movie_votes = Vote.where(user_id: current_user.id, movie_id: @movie.id).count
    
    if user_total_votes >= 3
      flash[:alert] = t('votes.limit_reached')  # 投票制限を超えた場合のメッセージ
    elsif user_movie_votes > 0
      flash[:alert] = t('votes.already_voted')  # 特定の映画に既に投票している場合
    else
      # 投票を記録
      Vote.create(user_id: current_user.id, movie_id: @movie.id)
      
      # ユーザーの投票数を増加
      current_user.increment!(:vote_count)
      
      flash[:notice] = t('votes.success', movie_title: @movie.title, current_count: user_total_votes + 1)  # 投票成功時のメッセージ
    end
    
    # 映画のページにリダイレクト
    redirect_to movie_path(@movie.id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admin/index.html.erb
<h1 class="text-2xl font-bold">ユーザー管理</h1>

<table class="table w-full table-zebra">  <%# テーブルのスタイリング %>
  <thead>
    <tr>
      <th>ID</th>
      <th>ユーザー名</th>
      <th>メール</th>
      <th>投票数</th>
      <th>レビュー数</th>
      <th>アクション</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name || '名前なし' %></td>  <%# ユーザー名 %>
        <td><%= user.email %></td>  <%# ユーザーメール %>
        <td><%= user.vote_count %></td>  <%# ユーザーの投票数 %>
        <td><%= Review.where(user_id: user.id).count %></td>  <%# ユーザーのレビュー数 %>
        <td>
          <%= link_to 'リセット', admin_reset_vote_count_path(user_id: user.id), data: { turbo_confirm: '本当にリセットしますか？', turbo_method: :post }, class: 'btn btn-error' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title>ConanCinemaReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render partial: 'shared/header' %>
    <% else %>
      <%= render partial: 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%#= render partial: 'shared/footer' %>
  </body>
</html>

app/views/pages/_page.html.erb
<div id="movie_<%= movie.id %>" class="card">
  <div class="text-content">
    <h3 class="text-xl font-semibold mb-2 truncate card-title"><%= movie.title %></h3>

    <% if movie.release_date.present? %>
      <p class="text-gray-600">公開日: <%= movie.release_date %></p>
    <% end %>

    <% if movie.poster_path.present? %>
      <%= image_tag("https://image.tmdb.org/t/p/w200#{movie.poster_path}", alt: "#{movie.title} ポスター", class: "rounded-lg mb-4 movie-poster") %>
    <% end %>

    <p class="text-gray-600">この映画への投票数: <%= Vote.where(movie_id: movie.id).count %></p>
  </div>
  <div class="flex justify-between items-center mt-4">
    <%= link_to '詳細', movie_path(movie.id), class: "btn btn-outline" %>
  </div>
</div>

<style>
  .card-title {
    font-size: 1.25rem; /* 20px */
    font-weight: bold;
    overflow: hidden;
    text-overflow: clip; /* テキストがはみ出た場合に切り捨てる */
    white-space: normal; /* テキストを折り返す */
    line-height: 1.5; /* 行間を適切に設定 */
    height: 3em; /* 高さを固定して均一な外観を保つ */
    display: -webkit-box;
    -webkit-line-clamp: 2; /* 2行に制限 */
    -webkit-box-orient: vertical;
  }

  .movie-poster {
    width: 100%; /* 画像をコンテナの幅に合わせる */
    max-width: 200px; /* 最大幅を200pxに制限 */
    height: 300px; /* 高さを固定 */
    object-fit: cover; /* 画像をコンテナに合わせてトリミング */
    margin: 0 auto; /* 画像を中央に配置 */
    display: block; /* 画像をブロック要素として扱う */
  }

  .card {
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    padding: 20px;
    margin-bottom: 20px;
    display: flex;
    flex-direction: column;
    justify-content: space-between; /* コンテンツ間のスペースを均等に分配 */
    min-height: 340px; /* 最小高さを設定 */
  }

</style>

app/views/pages/home.html.erb
<div class="container mx-auto px-4 py-6">  <!-- コンテナとパディング、中央寄せ -->
  <div class="text-lg mb-4">  <!-- 説明文 -->
    <h2 class="text-2xl font-semibold mt-4">最高のコナン映画を選ぼう</h2>
    <p>名探偵コナンファンのための映画レビューサイトへようこそ！<br>
    このサイトでは、投票数に基づいて映画のランキングを紹介しています。<br>
    詳細ページにて1人3票まで投票できるので、<br>
    あなたのお気に入りの映画を選んで、ランキングに反映させましょう。</p>

    <h2 class="text-2xl font-semibold mt-4">レビューを投稿しよう</h2>
    <p>映画に関するレビューも投稿できます。印象的だったシーンや、お気に入りのキャラクターについて、他のファンと意見を共有してください。レビューを読むことで、新たな視点から映画を楽しむことができます。</p>
    <p>最新映画もランキング対象なので、ネタバレは禁止でお願いいたします！</p>
    <p>現在、AmazonPrimeVideo・Huluで視聴することができるのでランキングを参考に視聴するのも良いかと思います。</p>
  </div>
  <br><br>
  <h1 class="text-3xl font-bold">映画一覧</h1>
  <div class="mt-12 overflow-hidden relative">  <!-- Swiperセクションとの間隔を大きく、overflow-hidden適用 -->
    <div class="swiper-container">  <!-- Swiperの中央配置 -->
      <div class="swiper-wrapper">  <!-- Swiperのスライドラッパー -->
        <% @movies.each do |movie| %>
          <div class="swiper-slide" style="width: 200px;">  <!-- スライドの幅を設定 -->
            <%= render 'pages/page', movie: movie %>  <!-- 映画カードのレンダリング -->
          </div>
        <% end %>
      </div>

      <!-- ナビゲーションボタン -->
      <div class="swiper-button-next btn btn-circle"></div>  <!-- DaisyUIのスタイル -->
      <div class="swiper-button-prev"></div>  <!-- DaisyUIのスタイル -->
    </div>
  </div>
</div>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
  document.addEventListener('turbo:load', () => {
    const swiper = new Swiper('.swiper-container', {
      slidesPerView: 1, // デフォルトでは1つのスライド
      spaceBetween: 10, // スライド間のスペース
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      // レスポンシブブレイクポイントの設定
      breakpoints: {
        // 768px以上の場合
        768: {
          slidesPerView: 3, // 3つのスライドを表示
          spaceBetween: 10 // スペースは同じで
        }
      }
    });
  });
</script>

<style>
  .swiper-button-next, .swiper-button-prev {
    color: blue;  /* 矢印ボタンの色を赤に変更 */
    background: white;  /* 背景色を白に変更 */
    border-radius: 50%;  /* 丸い形状にする */
    padding: 5px;
    top: 50%;  /* 常にコンテナの中央に配置 */
    transform: translateY(-50%);  /* ボタンの中心を正確に中央に合わせる */
  }

  @media (max-width: 768px) {
    .swiper-button-next, .swiper-button-prev {
      top: auto;  /* タブレットサイズではtopの設定を解除 */
      bottom: 10px;  /* コンテナの下部から10pxの位置に配置 */
      right: 10px;  /* 右側の余白を設定 */
    }
  }

  .swiper-button-next:hover, .swiper-button-prev:hover {
    color: white;  /* ホバー時の矢印の色を白に */
    background: blue;  /* ホバー時の背景色を赤に */
  }

  .container {
    max-width: 1200px;  /* 最大幅を設定 */
    margin: 0 auto;  /* 中央寄せ */
    padding: 16px;  /* パディングを設定 */
  }

  .swiper-slide {
    width: 200px;  /* デフォルトのスライド幅 */
  }

  @media (max-width: 768px) {
    .swiper-slide {
      width: 150px;  /* タブレットサイズではスライド幅を狭く */
    }
  }

  @media (max-width: 480px) {
    .swiper-slide {
      width: 100px;  /* スマートフォンサイズではさらに狭く */
    }
  }
</style>

app/views/shared/_before_login_header.html.erb
<header class="bg-primary flex w-full px-4 sm:px-6 lg:px-8">
  <div class="navbar container mx-auto flex justify-between">
    <div class="flex-initial">
      <%= link_to 'コナン映画レビュー', root_path, class: 'btn btn-primary btn-lg btn-block transition duration-300 ease-in-out transform hover:scale-110' %>
    </div>
    <div class="flex-initial">
      <ul class="menu menu-horizontal p-0">
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path, class: "btn" %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="bg-primary flex w-full px-4 sm:px-6 lg:px-8">
  <div class="navbar container mx-auto flex justify-between">
    <div class="flex justify-start">  <!-- 左揃えにするためのコンテナ -->
      <div class="flex-initial">
        <%= link_to 'コナン映画レビュー', root_path, class: 'btn btn-primary btn-lg btn-block transition duration-300 ease-in-out transform hover:scale-110' %>
      </div>
    </div>
    <div class="dropdown dropdown-left">
      <div tabindex="0" role="button" class="btn m-1">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" style="fill: none; stroke: currentColor; stroke-width: 2;">
          <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </div>
      <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52" style="z-index: 1001;">
        <% if current_user && current_user.email == ENV['ADMIN_EMAIL'] %>
          <li><%= link_to '管理画面', admin_path %></li>
        <% end %>
        <li><%= link_to '映画一覧', movies_path %></li>
        <li><%= link_to 'ユーザー編集', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  </div>
</header>